#ifndef APPCONST_H
#define APPCONST_H

#define S_ID "ID"
#define S_HEADER "Заголовок"
#define S_PATH "Путь"
#define S_AUTHOR "Автор"
#define S_SEX "Пол"
#define S_BIRTH_YEAR "Год рождения"
#define S_CREATE_YEAR "Год создания"
#define S_SPHERE "Сфера"
#define S_TEXT_TYPE "Тип текста"
#define S_TOPIC "Тематика"
#define S_STYLE "Стиль"
#define S_AUDIENCE_AGE "Возраст аудитории"
#define S_AUDIENCE_EDUCATION "Уровень аудитории"
#define S_AUDIENCE_SIZE "Размер аудитории"
#define S_SPEAKER_TYPE "Тип говорящего"

#define COL_ID "ID"
#define COL_NAME "NAME"
#define COL_HEXCOLOR "HEXCOLOR"
#define COL_PATTERN "PATTERN"
#define COL_TYPE "TYPE"
#define COL_PATTERN_ID "PATTERN_ID"
#define COL_SCHEME_ID "SCHEME_ID"
#define COL_PARENT_ID "PARENT_ID"
#define COL_STATEMENT "STATEMENT"
#define COL_SPEAKER_ID "SPEAKER_ID"
#define COL_BIRTH_YEAR "BIRTH_YEAR"
#define COL_REGEXP "REGEXP"
#define COL_PRIORITY "PRIORITY"
#define COL_USAGE_TYPE "USAGE_TYPE"
#define COL_SPEECH_ROLE "SPEACH_ROLE"
#define COL_STATEMENT_PLAIN "STATEMENT_PLAIN"
#define COL_PRIORITY "PRIORITY"
#define COL_ROLE "role"
#define COL_ACTOR "ACTOR"
#define COL_ACTIVE "active"
#define COL_SEX "SEX"
#define COL_PROFESSION "PROFESSION"
#define COL_HEADER "HEADER"

#define COL_AUTHOR "AUTHOR"
#define COL_CREATED "CREATED"
#define COL_PATH "PATH"
#define COL_PROJECT_ID "PROJECT_ID"
#define COL_SPEAKER_TYPE_ID "SPEAKER_TYPE_ID"

#define TAG_SPEECH "speech"
#define ATTR_ROLE "role"
#define ATTR_PROFESSION "profession"
#define ATTR_SEX "sex"
#define ATTR_ACTOR "actor"

#define GEN_STATEMENTS "GEN_STATEMENTS_ID"
#define GEN_SPEAKERS "GEN_SPEAKERS_ID"
#define GEN_REPLACE_PATTERNS "GEN_REPLACE_PATTERNS_ID"
#define GEN_SCHEME_PATTERNS "GEN_SCHEME_PATTERNS_ID"
#define GEN_HIGHLIGHT_SCHEMES "GEN_HIGHLIGHT_SCHEMES_ID"
#define GEN_PATTERNS "GEN_PATTERNS_ID"
#define GEN_PROJECTS "GEN_PROJECTS_ID"

#define DEF_LOG_DIR "logs"
#define DEF_LOG_EXT ".log"

#define PATH_DELIMITER "/"
#define MAX_STATEMENT_SIZE 5000
#define STATEMENT_SPLIT_SIZE 3000

#endif // APPCONST_H
